# characters.py
# api for the docs website coming soon.
# made by mindsetpro

from typing import Optional
from dataclasses import dataclass

@dataclass
class DBLCharacter:
    name: str
    charatags: Optional[str] = None
    id: Optional[int] = None

characters = [
    DBLCharacter(name=" Goku", charatags="DBL01-01H", id=1),
    DBLCharacter(name=" Gohan (Kid)", charatags="DBL01-36S", id=2),
    DBLCharacter(name=" Gohan (Kid)", charatags="DBL01-06H", id=3),
    DBLCharacter(name=" Piccolo", charatags="DBL01-07S", id=4),
    DBLCharacter(name=" Krillin", charatags="DBL01-33E", id=5),
    DBLCharacter(name=" Krillin", charatags="DBL01-09H", id=6),
    DBLCharacter(name=" Yamcha", charatags="DBL01-38E", id=7),
    DBLCharacter(name=" Tien", charatags="DBL01-11E", id=8),
    DBLCharacter(name=" Chiaotzu", charatags="DBL01-12E", id=9),
    DBLCharacter(name=" Raditz", charatags="DBL01-22H", id=10),
    DBLCharacter(name=" Saibaman", charatags="DBL01-23H", id=11),
    DBLCharacter(name=" Nappa", charatags="DBL01-19E", id=12),
    DBLCharacter(name=" Nappa", charatags="DBL01-20H", id=13),
    DBLCharacter(name=" Vegeta", charatags="DBL01-17S", id=14),
    DBLCharacter(name=" Goku", charatags="DBL-EVT-00S", id=15),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL01-04S", id=16),
    DBLCharacter(name="Fused with Nail Piccolo", charatags="DBL01-37E", id=17),
    DBLCharacter(name=" Vegeta", charatags="DBL01-39E", id=18),
    DBLCharacter(name=" Vegeta", charatags="DBL01-18H", id=19),
    DBLCharacter(name=" Zarbon", charatags="DBL01-25H", id=20),
    DBLCharacter(name=" Dodoria", charatags="DBL01-26H", id=21),
    DBLCharacter(name=" Guldo", charatags="DBL01-30H", id=22),
    DBLCharacter(name=" Burter", charatags="DBL01-29H", id=23),
    DBLCharacter(name=" Recoome", charatags="DBL01-27H", id=24),
    DBLCharacter(name=" Jeice", charatags="DBL01-28H", id=25),
    DBLCharacter(name=" Captain Ginyu", charatags="DBL01-45H", id=26),
    DBLCharacter(name=" Captain Ginyu", charatags="DBL01-44S", id=27),
    DBLCharacter(name="1st Form Frieza", charatags="DBL01-40E", id=28),
    DBLCharacter(name="1st Form Frieza", charatags="DBL01-24H", id=29),
    DBLCharacter(name="2nd Form Frieza", charatags="DBL01-42H", id=30),
    DBLCharacter(name="3rd Form Frieza", charatags="DBL01-43E", id=31),
    DBLCharacter(name="Final Form Frieza", charatags="DBL01-41S", id=32),
    DBLCharacter(name=" Mercenary Tao", charatags="DBL01-31E", id=33),
    DBLCharacter(name=" Pikkon", charatags="DBL01-34H", id=34),
    DBLCharacter(name=" Pikkon", charatags="DBL01-16S", id=35),
    DBLCharacter(name=" Jaco", charatags="DBL01-15H", id=36),
    DBLCharacter(name="Final Form Frost", charatags="DBL01-46E", id=37),
    DBLCharacter(name=" Pan", charatags="DBL01-05S", id=38),
    DBLCharacter(name=" Pan", charatags="DBL01-32H", id=39),
    DBLCharacter(name="Fused with Nail Piccolo", charatags="DBL01-08H", id=40),
    DBLCharacter(name=" Yamcha", charatags="DBL01-10H", id=41),
    DBLCharacter(name=" Tien", charatags="DBL01-13H", id=42),
    DBLCharacter(name=" Chiaotzu", charatags="DBL01-14H", id=43),
    DBLCharacter(name="Final Form Frost", charatags="DBL01-47H", id=44),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL-EVT-08S", id=45),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL02-01S", id=46),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL02-02S", id=47),
    DBLCharacter(name=" Android #20", charatags="DBL02-09E", id=48),
    DBLCharacter(name=" Android #19", charatags="DBL02-07E", id=49),
    DBLCharacter(name=" Turles", charatags="DBL02-13S", id=50),
    DBLCharacter(name=" Mai", charatags="DBL08-03S", id=51),
    DBLCharacter(name=" Trunks (Teen)", charatags="DBL02-03E", id=52),
    DBLCharacter(name=" Vegeta", charatags="DBL02-12E", id=53),
    DBLCharacter(name=" Turles", charatags="DBL02-14E", id=54),
    DBLCharacter(name=" Android #20", charatags="DBL02-10H", id=55),
    DBLCharacter(name=" Android #19", charatags="DBL02-08H", id=56),
    DBLCharacter(name=" Yamcha", charatags="DBL02-04H", id=57),
    DBLCharacter(name=" Saibaman", charatags="DBL02-06H", id=58),
    DBLCharacter(name=" Jaco", charatags="DBL02-05H", id=59),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL03-01S", id=60),
    DBLCharacter(name=" Krillin", charatags="DBL03-03S", id=61),
    DBLCharacter(name=" Android #17", charatags="DBL03-05S", id=62),
    DBLCharacter(name=" Android #18", charatags="DBL03-06S", id=63),
    DBLCharacter(name="1st Form Cell", charatags="DBL03-08E", id=64),
    DBLCharacter(name=" Master Roshi", charatags="DBL04-13E", id=65),
    DBLCharacter(name="Super Saiyan Cabba", charatags="DBL09-01S", id=66),
    DBLCharacter(name=" Android #18", charatags="DBL03-07E", id=68),
    DBLCharacter(name=" Cabba", charatags="DBL03-12H", id=69),
    DBLCharacter(name=" Master Roshi", charatags="DBL04-14H", id=70),
    DBLCharacter(name=" Android #17", charatags="DBL03-16E", id=71),
    DBLCharacter(name=" Goku", charatags="DBL03-02H", id=72),
    DBLCharacter(name="1st Form Cell", charatags="DBL03-09H", id=73),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL04-10S", id=75),
    DBLCharacter(name=" Goku (Youth)", charatags="DBL-EVT-01S", id=76),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL11-02S", id=77),
    DBLCharacter(name=" Bardock", charatags="DBL03-10S", id=78),
    DBLCharacter(name=" Demon King Piccolo", charatags="DBL05-08S", id=79),
    DBLCharacter(name="Legendary Super Saiyan Broly", charatags="DBL01-35S", id=80),
    DBLCharacter(name="1st Form Frieza", charatags="DBL03-13S", id=81),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL11-01S", id=82),
    DBLCharacter(name=" Trunks", charatags="DBL11-03E", id=83),
    DBLCharacter(name=" Demon King Piccolo", charatags="DBL05-09E", id=84),
    DBLCharacter(name=" Pan", charatags="DBL04-12E", id=85),
    DBLCharacter(name="1st Form Frieza", charatags="DBL04-07E", id=86),
    DBLCharacter(name=" Bardock", charatags="DBL04-06E", id=87),
    DBLCharacter(name=" Raditz", charatags="DBL01-21E", id=90),
    DBLCharacter(name=" Zarbon", charatags="DBL04-08E", id=91),
    DBLCharacter(name=" Dodoria", charatags="DBL04-09E", id=92),
    DBLCharacter(name=" Super Vegeta", charatags="DBL03-14S", id=93),
    DBLCharacter(name="Fused with Kami Piccolo", charatags="DBL05-05S", id=94),
    DBLCharacter(name=" Android #16", charatags="DBL05-06S", id=95),
    DBLCharacter(name="2nd Form Cell", charatags="DBL04-02E", id=96),
    DBLCharacter(name=" Cooler", charatags="DBL02-15S", id=97),
    DBLCharacter(name=" Thouser", charatags="DBL08-11E", id=99),
    DBLCharacter(name=" Cooler", charatags="DBL07-06E", id=100),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL04-01S", id=101),
    DBLCharacter(name=" Trunks (Kid)", charatags="DBL05-04E", id=102),
    DBLCharacter(name=" Goten (Kid)", charatags="DBL05-02E", id=103),
    DBLCharacter(name="Perfect Form Cell", charatags="DBL23-03E", id=104),
    DBLCharacter(name=" Thouser", charatags="DBL08-12H", id=105),
    DBLCharacter(name=" Android #16", charatags="DBL06-09E", id=106),
    DBLCharacter(name=" Android #18", charatags="DBL06-10S", id=107),
    DBLCharacter(name="Perfect Form Cell", charatags="DBL04-04S", id=108),
    DBLCharacter(name=" Super Trunks", charatags="DBL03-15S", id=109),
    DBLCharacter(name=" Cell Jr.", charatags="DBL04-05H", id=110),
    DBLCharacter(name="Super Saiyan 2 Gohan (Youth)", charatags="DBL04-11S", id=111),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL06-11S", id=112),
    DBLCharacter(name=" Majin Buu: Good", charatags="DBL06-06S", id=113),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL26-01E", id=114),
    DBLCharacter(name="World Champion Hercule", charatags="DBL05-07S", id=115),
    DBLCharacter(name=" Majin Buu: Good", charatags="DBL21-04E", id=117),
    DBLCharacter(name=" Gohan (Youth)", charatags="DBL06-03E", id=118),
    DBLCharacter(name=" Cell Jr.", charatags="DBL06-05E", id=119),
    DBLCharacter(name=" Turles", charatags="DBL06-08H", id=120),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL06-02H", id=121),
    DBLCharacter(name=" Krillin", charatags="DBL06-04H", id=122),
    DBLCharacter(name="Super Saiyan Gohan", charatags="DBL08-01S", id=123),
    DBLCharacter(name="Super Saiyan 2 Trunks (Adult)", charatags="DBL08-02S", id=124),
    DBLCharacter(name=" Goku", charatags="DBL07-08S", id=125),
    DBLCharacter(name=" Goku Black", charatags="DBL06-13S", id=126),
    DBLCharacter(name=" Zamasu", charatags="DBL08-14S", id=127),
    DBLCharacter(name="Super Saiyan Kale (Berserk)", charatags="DBL09-04S", id=128),
    DBLCharacter(name=" Mai", charatags="DBL09-08E", id=130),
    DBLCharacter(name=" Goku Black", charatags="DBL15-02S", id=131),
    DBLCharacter(name=" Vegeta", charatags="DBL07-10S", id=133),
    DBLCharacter(name=" Zamasu", charatags="DBL16-05E", id=134),
    DBLCharacter(name=" Android #17", charatags="DBL08-04E", id=136),
    DBLCharacter(name=" Android #18", charatags="DBL08-05E", id=137),
    DBLCharacter(name=" Vegeta", charatags="DBL03-04E", id=138),
    DBLCharacter(name="2nd Form Cell", charatags="DBL04-03H", id=139),
    DBLCharacter(name=" Vegito", charatags="DBL-EVT-07S", id=140),
    DBLCharacter(name="Super Saiyan Trunks (Kid)", charatags="DBL05-03S", id=141),
    DBLCharacter(name="Super Saiyan Goten (Kid)", charatags="DBL05-01S", id=142),
    DBLCharacter(name=" Majin Vegeta", charatags="DBL06-12S", id=143),
    DBLCharacter(name="Super Saiyan Gotenks", charatags="DBL06-01S", id=144),
    DBLCharacter(name="King of the Demon Realm Dabura", charatags="DBL06-07S", id=145),
    DBLCharacter(name="King of the Demon Realm Dabura", charatags="DBL26-04E", id=146),
    DBLCharacter(name=" Broly: Fury", charatags="DBL-EVT-02S", id=147),
    DBLCharacter(name=" Super Gogeta", charatags="DBL05-10S", id=148),
    DBLCharacter(name=" Super Janemba", charatags="DBL05-11S", id=149),
    DBLCharacter(name="Super Saiyan 2 Goku", charatags="DBL07-01S", id=150),
    DBLCharacter(name="Super Saiyan Bardock", charatags="DBL07-04S", id=151),
    DBLCharacter(name=" Chilled", charatags="DBL07-05S", id=152),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL07-03E", id=154),
    DBLCharacter(name=" Pan: Honey", charatags="DBL08-07E", id=155),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL07-02E", id=156),
    DBLCharacter(name="Super Saiyan Gohan (Teen)", charatags="DBL-EVT-12S", id=157),
    DBLCharacter(name=" Fasha", charatags="DBL08-09E", id=158),
    DBLCharacter(name=" Tora", charatags="DBL08-08E", id=159),
    DBLCharacter(name=" Goku", charatags="DBL02-11S", id=160),
    DBLCharacter(name=" Cabba", charatags="DBL03-11E", id=161),
    DBLCharacter(name=" Nappa (Young)", charatags="DBL-EVT-11S", id=162),
    DBLCharacter(name=" Nappa", charatags="DBL39-04S", id=163),
    DBLCharacter(name="Super Saiyan Broly", charatags="DBL07-07S", id=164),
    DBLCharacter(name="Super Saiyan God Goku", charatags="DBL07-09S", id=165),
    DBLCharacter(name="God of Destruction Beerus", charatags="DBL07-11S", id=166),
    DBLCharacter(name=" Boujack", charatags="DBL08-13S", id=167),
    DBLCharacter(name="Final Form Cooler", charatags="DBL08-10S", id=168),
    DBLCharacter(name=" Trunks (Youth)", charatags="DBL-EVT-03S", id=169),
    DBLCharacter(name=" Whis", charatags="DBL13-05E", id=170),
    DBLCharacter(name=" Gohan", charatags="DBL08-06E", id=171),
    DBLCharacter(name="Super Saiyan 2 Caulifla", charatags="DBL09-03S", id=172),
    DBLCharacter(name=" Ribrianne", charatags="DBL11-07S", id=173),
    DBLCharacter(name=" Chi-Chi", charatags="DBL09-06S", id=174),
    DBLCharacter(name=" Bulma (Youth)", charatags="DBL09-05S", id=175),
    DBLCharacter(name=" Videl", charatags="DBL09-07S", id=176),
    DBLCharacter(name=" Launch", charatags="DBL31-05S", id=177),
    DBLCharacter(name=" Caulifla", charatags="DBL09-02E", id=178),
    DBLCharacter(name=" Kakunsa", charatags="DBL16-08S", id=179),
    DBLCharacter(name=" Rozie", charatags="DBL16-09S", id=180),
    DBLCharacter(name=" Chi-Chi", charatags="DBL21-03E", id=181),
    DBLCharacter(name=" Videl", charatags="DBL24-07H", id=182),
    DBLCharacter(name=" Great Saiyaman 1", charatags="DBL-EVT-05S", id=183),
    DBLCharacter(name=" Great Saiyaman 2", charatags="DBL11-06S", id=184),
    DBLCharacter(name="Super Saiyan God Vegeta", charatags="DBL09-09S", id=185),
    DBLCharacter(name=" Ultimate Gohan", charatags="DBL10-02S", id=186),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL10-01S", id=187),
    DBLCharacter(name="Super Saiyan 2 Vegeta", charatags="DBL10-03S", id=188),
    DBLCharacter(name="Super Namekian Lord Slug", charatags="DBL10-10S", id=189),
    DBLCharacter(name=" Perfect Cell", charatags="DBL10-09S", id=190),
    DBLCharacter(name="Super Saiyan 2 Gohan (Youth)", charatags="DBL10-06S", id=191),
    DBLCharacter(name=" Gogeta", charatags="DBL10-11S", id=192),
    DBLCharacter(name=" Gotenks", charatags="DBL-EVT-04S", id=193),
    DBLCharacter(name=" Trunks (Teen)", charatags="DBL10-07E", id=194),
    DBLCharacter(name=" Tien", charatags="DBL10-08E", id=195),
    DBLCharacter(name=" Majin Buu: Pure Evil", charatags="DBL10-05E", id=196),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL10-04E", id=197),
    DBLCharacter(name=" Hyper Meta-Rilldo", charatags="DBL11-04S", id=198),
    DBLCharacter(name="Super Saiyan 3 Gotenks", charatags="DBL11-08S", id=199),
    DBLCharacter(name=" Buu: Super", charatags="DBL11-09S", id=200),
    DBLCharacter(name="Taitans Yamcha", charatags="DBL-EVT-06S", id=201),
    DBLCharacter(name="Super Namekian Lord Slug", charatags="DBL11-10E", id=202),
    DBLCharacter(name=" Bulma (Youth)", charatags="DBL11-05E", id=203),
    DBLCharacter(name="Super Saiyan Goten (Kid)", charatags="DBL12-06S", id=204),
    DBLCharacter(name="Super Saiyan Gohan (Teen)", charatags="DBL12-05S", id=205),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL12-04S", id=206),
    DBLCharacter(name="Legendary Super Saiyan Broly", charatags="DBL12-01S", id=207),
    DBLCharacter(name=" Metal Cooler", charatags="DBL12-02S", id=208),
    DBLCharacter(name=" Zangya", charatags="DBL15-04E", id=209),
    DBLCharacter(name=" Videl", charatags="DBL12-03E", id=210),
    DBLCharacter(name="World Champion Hercule", charatags="DBL24-11H", id=212),
    DBLCharacter(name="Fused with Kami Piccolo", charatags="DBL-EVT-09S", id=213),
    DBLCharacter(name=" Boujack", charatags="DBL15-03E", id=214),
    DBLCharacter(name="Ultimate Gohan Absorbed Buu: Super", charatags="DBL13-09S", id=215),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL13-01S", id=216),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL13-02S", id=217),
    DBLCharacter(name=" Golden Frieza", charatags="DBL13-06S", id=218),
    DBLCharacter(name="Final Form Frieza: Full Power", charatags="DBL15-06S", id=219),
    DBLCharacter(name=" Goku", charatags="DBL15-05S", id=220),
    DBLCharacter(name=" Super Janemba", charatags="DBL13-08E", id=221),
    DBLCharacter(name=" Chilled", charatags="DBL13-07E", id=222),
    DBLCharacter(name="God of Destruction Beerus", charatags="DBL13-04E", id=223),
    DBLCharacter(name=" Super Vegito", charatags="DBL13-03S", id=224),
    DBLCharacter(name=" Buu: Kid", charatags="DBL17-06S", id=225),
    DBLCharacter(name=" Trunks (Teen)", charatags="DBL14-04S", id=226),
    DBLCharacter(name=" Android #13", charatags="DBL14-05S", id=227),
    DBLCharacter(name=" Android #14", charatags="DBL14-02S", id=228),
    DBLCharacter(name=" Android #15", charatags="DBL14-03S", id=229),
    DBLCharacter(name=" Vados", charatags="DBL28-06S", id=230),
    DBLCharacter(name=" Guldo", charatags="DBL14-09E", id=231),
    DBLCharacter(name=" Burter", charatags="DBL14-07E", id=232),
    DBLCharacter(name=" Recoome", charatags="DBL14-06E", id=233),
    DBLCharacter(name=" Jeice", charatags="DBL14-08E", id=234),
    DBLCharacter(name=" Captain Ginyu", charatags="DBL14-10E", id=235),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL15-07S", id=236),
    DBLCharacter(name=" Hit", charatags="DBL15-08S", id=237),
    DBLCharacter(name="Super Saiyan Gohan (Youth)", charatags="DBL17-01S", id=238),
    DBLCharacter(name=" Goku", charatags="DBL16-10S", id=240),
    DBLCharacter(name=" Super #17", charatags="DBL16-13S", id=241),
    DBLCharacter(name=" Fusion Android #13", charatags="DBL16-02S", id=242),
    DBLCharacter(name=" Goku", charatags="DBL16-01S", id=243),
    DBLCharacter(name=" Android #18", charatags="DBL16-07S", id=244),
    DBLCharacter(name="Bunny Girl Bulma (Youth)", charatags="DBL16-06S", id=245),
    DBLCharacter(name="Goku Captain Ginyu", charatags="DBL-EVT-10S", id=246),
    DBLCharacter(name=" Gohan (Kid)", charatags="DBL16-11E", id=247),
    DBLCharacter(name=" Krillin", charatags="DBL16-12E", id=248),
    DBLCharacter(name=" Nail", charatags="DBL16-03E", id=249),
    DBLCharacter(name=" Nail", charatags="DBL16-04H", id=250),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL17-05S", id=251),
    DBLCharacter(name=" Goku", charatags="DBL22-01S", id=252),
    DBLCharacter(name=" Piccolo", charatags="DBL22-03S", id=253),
    DBLCharacter(name="God of Destruction Champa", charatags="DBL28-05S", id=254),
    DBLCharacter(name=" Bardock", charatags="DBL19-01S", id=255),
    DBLCharacter(name=" Full Power Boujack", charatags="DBL17-03S", id=256),
    DBLCharacter(name=" Vegeta", charatags="DBL14-01S", id=257),
    DBLCharacter(name=" Gohan", charatags="DBL15-01S", id=258),
    DBLCharacter(name=" Raditz", charatags="DBL22-04S", id=259),
    DBLCharacter(name="Ultimate Gohan Absorbed Buu: Super", charatags="DBL-EVT-16S", id=260),
    DBLCharacter(name=" Buu: Kid", charatags="DBL-EVT-37S", id=261),
    DBLCharacter(name="Legendary Super Saiyan Broly", charatags="DBL17-02E", id=262),
    DBLCharacter(name=" Android #13", charatags="DBL17-04E", id=263),
    DBLCharacter(name="Super Saiyan Rosé Goku Black", charatags="DBL18-06S", id=264),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL18-05S", id=265),
    DBLCharacter(name=" Cooler", charatags="DBL18-03S", id=266),
    DBLCharacter(name="Final Form Frieza", charatags="DBL18-01S", id=268),
    DBLCharacter(name=" Shisami", charatags="DBL18-04E", id=269),
    DBLCharacter(name="Super Saiyan 4 Goku", charatags="DBL19-05S", id=270),
    DBLCharacter(name="Super Saiyan 4 Vegeta", charatags="DBL19-07S", id=271),
    DBLCharacter(name=" Nuova Shenron", charatags="DBL35-04S", id=272),
    DBLCharacter(name=" Syn Shenron", charatags="DBL21-01S", id=273),
    DBLCharacter(name=" Eis Shenron", charatags="DBL35-03S", id=275),
    DBLCharacter(name="Hero Tapion", charatags="DBL19-03S", id=276),
    DBLCharacter(name=" Broly: Cheelai (Assist)", charatags="DBL22-09S", id=277),
    DBLCharacter(name="Kakarot Goku", charatags="DBL-EVT-14S", id=278),
    DBLCharacter(name=" Buu: Super", charatags="DBL19-04E", id=279),
    DBLCharacter(name=" Goku", charatags="DBL19-06E", id=280),
    DBLCharacter(name=" Trunks (Kid)", charatags="DBL19-02E", id=281),
    DBLCharacter(name="2nd Form Frieza", charatags="DBL18-02E", id=282),
    DBLCharacter(name=" Super Trunks", charatags="DBL24-06E", id=283),
    DBLCharacter(name=" Hyper Meta-Rilldo", charatags="DBL19-09E", id=284),
    DBLCharacter(name="Super Saiyan God SS Gogeta", charatags="DBL30-01S", id=285),
    DBLCharacter(name="Super Saiyan God Goku", charatags="DBL20-05S", id=286),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL20-06S", id=287),
    DBLCharacter(name=" Super Gogeta", charatags="DBL20-01S", id=288),
    DBLCharacter(name=" Super Janemba", charatags="DBL20-02S", id=289),
    DBLCharacter(name=" Super Baby 2", charatags="DBL19-08S", id=290),
    DBLCharacter(name=" Android #14", charatags="DBL20-03E", id=291),
    DBLCharacter(name=" Android #15", charatags="DBL20-04E", id=292),
    DBLCharacter(name="Super Saiyan 2 Kefla", charatags="DBL23-05S", id=293),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL23-01S", id=294),
    DBLCharacter(name="1st Form Cell", charatags="DBL23-02S", id=295),
    DBLCharacter(name=" Baby Vegeta", charatags="DBL21-02S", id=296),
    DBLCharacter(name=" Android #21", charatags="DBL-EVT-13S", id=297),
    DBLCharacter(name=" Android #21: Evil", charatags="DBL21-05S", id=298),
    DBLCharacter(name=" Android #21", charatags="DBL-EVT-42S", id=299),
    DBLCharacter(name=" Android #21: Good", charatags="DBL31-02S", id=300),
    DBLCharacter(name=" Basil", charatags="DBL28-03S", id=301),
    DBLCharacter(name=" Bergamo", charatags="DBL28-01S", id=302),
    DBLCharacter(name=" Lavender", charatags="DBL28-02S", id=303),
    DBLCharacter(name="1st Form Frieza", charatags="DBL22-05S", id=304),
    DBLCharacter(name=" Bardock", charatags="DBL22-02S", id=305),
    DBLCharacter(name=" Vegito", charatags="DBL22-08S", id=306),
    DBLCharacter(name=" Shugesh", charatags="DBL22-07E", id=307),
    DBLCharacter(name=" Borgos", charatags="DBL22-06E", id=308),
    DBLCharacter(name=" Mercenary Tao", charatags="DBL24-12H", id=309),
    DBLCharacter(name="Super Kaioken Goku", charatags="DBL24-13S", id=310),
    DBLCharacter(name=" Pikkon", charatags="DBL24-15S", id=311),
    DBLCharacter(name=" Kale", charatags="DBL47-04E", id=312),
    DBLCharacter(name="Super Saiyan Gotenks", charatags="DBL23-04S", id=313),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL25-04S", id=314),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL25-05S", id=315),
    DBLCharacter(name=" Goku (Youth)", charatags="DBL24-14E", id=316),
    DBLCharacter(name=" Hit", charatags="DBL25-06E", id=317),
    DBLCharacter(name="Super Saiyan God SS Vegito", charatags="DBL24-01S", id=318),
    DBLCharacter(name="Super Saiyan Trunks (Adult) (Rage)", charatags="DBL24-05S", id=319),
    DBLCharacter(name=" Fusion Zamasu", charatags="DBL24-08S", id=320),
    DBLCharacter(name=" Omega Shenron", charatags="DBL24-09S", id=321),
    DBLCharacter(name="Super Full Power Saiyan 4 Goku", charatags="DBL24-03S", id=322),
    DBLCharacter(name=" Syn Shenron", charatags="DBL24-10E", id=323),
    DBLCharacter(name=" Gogeta", charatags="DBL24-02E", id=324),
    DBLCharacter(name=" Super Vegeta", charatags="DBL24-04E", id=325),
    DBLCharacter(name=" Gohan (Adult)", charatags="DBL26-02S", id=326),
    DBLCharacter(name="Gotenks Absorbed Buu: Super", charatags="DBL26-03S", id=327),
    DBLCharacter(name="Wasteland Bandit Yamcha", charatags="DBL31-03S", id=328),
    DBLCharacter(name=" Tien", charatags="DBL25-03E", id=329),
    DBLCharacter(name=" Krillin", charatags="DBL25-01E", id=330),
    DBLCharacter(name=" Yamcha", charatags="DBL25-02E", id=331),
    DBLCharacter(name=" Bido", charatags="DBL36-06E", id=332),
    DBLCharacter(name=" Bujin", charatags="DBL36-07E", id=333),
    DBLCharacter(name=" Gokua", charatags="DBL36-05E", id=334),
    DBLCharacter(name=" Hit", charatags="DBL33-04S", id=337),
    DBLCharacter(name=" Turles", charatags="DBL25-08S", id=338),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL25-07S", id=339),
    DBLCharacter(name=" Jiren", charatags="DBL29-06S", id=340),
    DBLCharacter(name=" Toppo", charatags="DBL29-07S", id=341),
    DBLCharacter(name=" Dyspo", charatags="DBL29-08S", id=342),
    DBLCharacter(name=" Goten (Kid)", charatags="DBL27-02S", id=343),
    DBLCharacter(name=" Trunks (Kid)", charatags="DBL27-03S", id=344),
    DBLCharacter(name="Perfect Form Cell", charatags="DBL26-08S", id=345),
    DBLCharacter(name=" Vegeta", charatags="DBL26-06S", id=346),
    DBLCharacter(name="Super Saiyan 2 Goku", charatags="DBL26-05E", id=347),
    DBLCharacter(name=" Videl", charatags="DBL26-07E", id=348),
    DBLCharacter(name=" Great Saiyaman 1 & 2 (Assist)", charatags="DBL27-05S", id=349),
    DBLCharacter(name=" Goku Black", charatags="DBL27-06S", id=350),
    DBLCharacter(name=" Ribrianne", charatags="DBL27-07E", id=351),
    DBLCharacter(name=" Kakunsa", charatags="DBL28-04E", id=352),
    DBLCharacter(name=" Rozie", charatags="DBL28-07E", id=353),
    DBLCharacter(name=" Gohan (Kid)", charatags="DBL27-01E", id=354),
    DBLCharacter(name=" Yurin", charatags="DBL47-03E", id=362),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL29-01S", id=363),
    DBLCharacter(name=" Metal Cooler", charatags="DBL29-02S", id=364),
    DBLCharacter(name=" Full Power Boujack", charatags="DBL29-03E", id=365),
    DBLCharacter(name="Ultra Instinct -Sign- Goku", charatags="DBL29-04S", id=366),
    DBLCharacter(name="Final Form Frieza", charatags="DBL29-05E", id=367),
    DBLCharacter(name="Super Saiyan Broly: Full Power", charatags="DBL30-03S", id=370),
    DBLCharacter(name="Final Form Frieza", charatags="DBL30-02S", id=371),
    DBLCharacter(name=" Broly", charatags="DBL30-04E", id=372),
    DBLCharacter(name=" Vegeta", charatags="DBL-EVT-15S", id=373),
    DBLCharacter(name=" Goku", charatags="DBL-EVT-40S", id=374),
    DBLCharacter(name="Super Saiyan Gohan", charatags="DBL31-01S", id=375),
    DBLCharacter(name=" Master Roshi", charatags="DBL31-04E", id=376),
    DBLCharacter(name=" Buu: Kid", charatags="DBL32-02S", id=377),
    DBLCharacter(name=" Vegeta", charatags="DBL32-01S", id=378),
    DBLCharacter(name=" Bulma (Youth)", charatags="DBL-EVT-THX1000", id=379),
    DBLCharacter(name="Super Saiyan Broly", charatags="DBL32-05S", id=380),
    DBLCharacter(name=" Demon King Piccolo (Aged)", charatags="DBL32-04S", id=381),
    DBLCharacter(name=" Trunks (Youth)", charatags="DBL32-03E", id=382),
    DBLCharacter(name="Super Saiyan Rosé Goku Black", charatags="DBL33-02S", id=383),
    DBLCharacter(name=" Trunks: Mai (Assist)", charatags="DBL33-01S", id=384),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL-EVT-17U", id=385),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL33-03S", id=386),
    DBLCharacter(name=" Goku Black", charatags="DBL34-02E", id=387),
    DBLCharacter(name="Super Saiyan 4 Goku", charatags="DBL34-01S", id=388),
    DBLCharacter(name=" Android #18", charatags="DBL34-04S", id=389),
    DBLCharacter(name=" Android #17", charatags="DBL34-03S", id=390),
    DBLCharacter(name=" Baby Vegeta", charatags="DBL34-05E", id=391),
    DBLCharacter(name="Super Saiyan 4 Gogeta", charatags="DBL35-01S", id=392),
    DBLCharacter(name=" Super #17", charatags="DBL35-06E", id=393),
    DBLCharacter(name=" Super Baby 2", charatags="DBL35-07E", id=394),
    DBLCharacter(name="Half-Corrupted Fusion Zamasu", charatags="DBL35-08S", id=395),
    DBLCharacter(name="Super Saiyan God SS Vegito", charatags="DBL35-02S", id=396),
    DBLCharacter(name="Super Saiyan 2 Kefla", charatags="DBL35-10S", id=397),
    DBLCharacter(name="Super Saiyan 3 Gotenks", charatags="DBL35-05E", id=398),
    DBLCharacter(name="Super Saiyan Rosé Goku Black", charatags="DBL35-09E", id=399),
    DBLCharacter(name=" Vegeta", charatags="DBL-EVT-24U", id=400),
    DBLCharacter(name=" Goku", charatags="DBL-EVT-18S", id=401),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL-EVT-19S", id=402),
    DBLCharacter(name="Super Saiyan 2 Goku", charatags="DBL-EVT-20S", id=403),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL-EVT-21S", id=404),
    DBLCharacter(name="Super Saiyan God Goku", charatags="DBL-EVT-22S", id=405),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL-EVT-23S", id=406),
    DBLCharacter(name="Super Saiyan Gohan (Youth)", charatags="DBL36-01S", id=409),
    DBLCharacter(name=" Zangya", charatags="DBL36-04E", id=410),
    DBLCharacter(name=" Boujack", charatags="DBL36-03S", id=411),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL36-02S", id=412),
    DBLCharacter(name="Final Form Frieza: Full Power", charatags="DBL37-02S", id=414),
    DBLCharacter(name=" Appule", charatags="DBL-EVT-25E", id=415),
    DBLCharacter(name=" Ramon", charatags="DBL-EVT-26E", id=416),
    DBLCharacter(name=" Orlen", charatags="DBL-EVT-27E", id=417),
    DBLCharacter(name=" Nabana", charatags="DBL-EVT-28E", id=418),
    DBLCharacter(name=" Roberry", charatags="DBL-EVT-29E", id=419),
    DBLCharacter(name=" Raspberry", charatags="DBL-EVT-52E", id=420),
    DBLCharacter(name=" Navel", charatags="DBL-EVT-53E", id=421),
    DBLCharacter(name=" Monrei", charatags="DBL-EVT-54E", id=422),
    DBLCharacter(name=" Guprei", charatags="DBL-EVT-55E", id=423),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL37-03S", id=424),
    DBLCharacter(name=" Majuub", charatags="DBL37-04S", id=425),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL37-01E", id=426),
    DBLCharacter(name="Legendary Super Saiyan Broly", charatags="DBL-EVT-30S", id=427),
    DBLCharacter(name="Super Saiyan God SS Evolved Vegeta", charatags="DBL38-01S", id=428),
    DBLCharacter(name=" Jiren", charatags="DBL38-02E", id=429),
    DBLCharacter(name="God of Destruction Toppo", charatags="DBL38-03S", id=430),
    DBLCharacter(name="Super Saiyan 2 Caulifla: Kale (Assist)", charatags="DBL38-04S", id=431),
    DBLCharacter(name=" Perfect Cell", charatags="DBL40-02S", id=432),
    DBLCharacter(name=" Vegeta", charatags="DBL39-01S", id=433),
    DBLCharacter(name=" Yajirobe", charatags="DBL39-02E", id=434),
    DBLCharacter(name=" Saibaman", charatags="DBL-EVT-31E", id=435),
    DBLCharacter(name=" Kaiwareman", charatags="DBL-EVT-32E", id=436),
    DBLCharacter(name=" Kyukonman", charatags="DBL-EVT-33E", id=437),
    DBLCharacter(name=" Tennenman", charatags="DBL-EVT-34E", id=438),
    DBLCharacter(name=" Jinkouman", charatags="DBL-EVT-35E", id=439),
    DBLCharacter(name=" Copyman", charatags="DBL-EVT-36E", id=440),
    DBLCharacter(name=" Gohan (Kid): Piccolo (Assist)", charatags="DBL39-03S", id=441),
    DBLCharacter(name="Super Saiyan 2 Gohan (Youth)", charatags="DBL40-01E", id=442),
    DBLCharacter(name=" Omega Shenron", charatags="DBL-EVT-38U", id=443),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL40-03S", id=444),
    DBLCharacter(name="Fused with Nail Piccolo", charatags="DBL40-04S", id=445),
    DBLCharacter(name="Super Saiyan Rosé Goku Black", charatags="DBL-EVT-39S", id=447),
    DBLCharacter(name="Super Saiyan God SS Goku & Vegeta", charatags="DBL41-01S", id=448),
    DBLCharacter(name=" Broly", charatags="DBL41-03S", id=449),
    DBLCharacter(name="Final Form Frieza", charatags="DBL41-05E", id=450),
    DBLCharacter(name="Super Saiyan Trunks (Adult)", charatags="DBL41-02S", id=451),
    DBLCharacter(name=" Zamasu: Goku Black (Assist)", charatags="DBL41-04S", id=452),
    DBLCharacter(name=" Mai", charatags="DBL41-06E", id=453),
    DBLCharacter(name=" Super Gogeta", charatags="DBL42-01U", id=454),
    DBLCharacter(name="1st Form Frieza", charatags="DBL-EVT-41S", id=455),
    DBLCharacter(name=" Bardock", charatags="DBL43-01S", id=456),
    DBLCharacter(name=" Tora", charatags="DBL43-02E", id=457),
    DBLCharacter(name=" Fasha", charatags="DBL43-03E", id=458),
    DBLCharacter(name="Kaioken Goku", charatags="DBL43-04S", id=459),
    DBLCharacter(name="Final Form Frieza", charatags="DBL43-05S", id=460),
    DBLCharacter(name=" Android #18", charatags="DBL-EVT-43S", id=461),
    DBLCharacter(name=" Jiren: Full Power", charatags="DBL44-01S", id=462),
    DBLCharacter(name="God of Destruction Beerus", charatags="DBL44-02S", id=463),
    DBLCharacter(name=" Toppo", charatags="DBL44-03E", id=464),
    DBLCharacter(name=" Dyspo", charatags="DBL44-04E", id=465),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL-EVT-44S", id=466),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL-EVT-45S", id=467),
    DBLCharacter(name="Super Saiyan God SS Kaioken Goku", charatags="DBL45-01U", id=468),
    DBLCharacter(name=" Golden Frieza", charatags="DBL45-02S", id=469),
    DBLCharacter(name=" Whis", charatags="DBL45-03S", id=470),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL-EVT-46S", id=471),
    DBLCharacter(name=" Android #17 & Android #18", charatags="DBL46-01S", id=472),
    DBLCharacter(name=" Gohan & Trunks (Youth)", charatags="DBL46-02E", id=473),
    DBLCharacter(name="Super Saiyan Gogeta", charatags="DBL-EVT-50S", id=474),
    DBLCharacter(name=" Gamma 1", charatags="DBL46-03S", id=475),
    DBLCharacter(name=" Gamma 2", charatags="DBL46-04S", id=476),
    DBLCharacter(name="Ultra Instinct Goku", charatags="DBL47-01S", id=477),
    DBLCharacter(name="Super Saiyan Vegeta", charatags="DBL47-02S", id=478),
    DBLCharacter(name=" Goku", charatags="DBL-EVT-47S", id=479),
    DBLCharacter(name=" Krillin", charatags="DBL-EVT-48S", id=480),
    DBLCharacter(name=" Tien", charatags="DBL-EVT-49S", id=481),
    DBLCharacter(name="Super Saiyan 3 Goku", charatags="DBL48-01S", id=482),
    DBLCharacter(name="Hero Tapion", charatags="DBL48-02S", id=483),
    DBLCharacter(name=" Turles", charatags="DBL48-03E", id=484),
    DBLCharacter(name="Final Form Cooler", charatags="DBL48-04E", id=485),
    DBLCharacter(name=" Majin Vegeta", charatags="DBL-EVT-51S", id=486),
    DBLCharacter(name=" Super Vegito", charatags="DBL49-01U", id=487),
    DBLCharacter(name="Ultimate Gohan Absorbed Buu: Super", charatags="DBL49-03S", id=488),
    DBLCharacter(name=" Tien", charatags="DBL49-02S", id=489),
    DBLCharacter(name="Perfect Form Cell", charatags="DBL-EVT-56S", id=490),
    DBLCharacter(name="Beast Gohan", charatags="DBL52-01S", id=491),
    DBLCharacter(name="Power Awakening Piccolo", charatags="DBL52-03S", id=492),
    DBLCharacter(name=" Metal Cooler", charatags="DBL-EVT-57S", id=493),
    DBLCharacter(name="Final Form Cooler", charatags="DBL51-01S", id=494),
    DBLCharacter(name="Legendary Super Saiyan Broly", charatags="DBL51-03U", id=495),
    DBLCharacter(name=" Thouser", charatags="DBL51-02E", id=496),
    DBLCharacter(name="Super Saiyan Trunks (Teen)", charatags="DBL50-01S", id=497),
    DBLCharacter(name=" Mecha Frieza", charatags="DBL50-02S", id=498),
    DBLCharacter(name=" Goku Black", charatags="DBL50-03S", id=499),
    DBLCharacter(name=" Pan", charatags="DBL52-02S", id=500),
    DBLCharacter(name="Super Saiyan 4 Goku & Vegeta", charatags="DBL53-01S", id=501),
    DBLCharacter(name=" Android #17", charatags="DBL53-03S", id=502),
    DBLCharacter(name=" Buu: Super", charatags="DBL-EVT-65S", id=503),
    DBLCharacter(name=" Super #17", charatags="DBL-EVT-58S", id=507),
    DBLCharacter(name="Super Saiyan God SS Gogeta", charatags="DBL54-05U", id=508),
    DBLCharacter(name=" Android #18", charatags="DBL55-02E", id=509),
    DBLCharacter(name=" Android #17", charatags="DBL55-01S", id=510),
    DBLCharacter(name=" Hit", charatags="DBL55-03U", id=511),
    DBLCharacter(name="Super Saiyan 2 & Super Saiyan God SS Trunks (Adult) & Vegeta", charatags="DBL54-03S", id=514),
    DBLCharacter(name=" Zamasu", charatags="DBL54-04S", id=515),
    DBLCharacter(name=" Fusion Zamasu", charatags="DBL-EVT-60S", id=516),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL54-01E", id=517),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL54-02E", id=518),
    DBLCharacter(name="Super Saiyan Broly: Full Power", charatags="DBL-EVT-61S", id=519),
    DBLCharacter(name=" Omega Shenron", charatags="DBL53-04E", id=520),
    DBLCharacter(name=" Majuub", charatags="DBL53-02E", id=521),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL-EVT-59S", id=522),
    DBLCharacter(name=" Zahha", charatags="DBL00-02", id=524),
    DBLCharacter(name=" Saiyan in Red", charatags="DBL00-03", id=525),
    DBLCharacter(name="Super Saiyan 2 Kefla", charatags="DBL-EVT-62S", id=526),
    DBLCharacter(name="Super Saiyan God SS Goku", charatags="DBL56-01S", id=527),
    DBLCharacter(name=" Master Roshi", charatags="DBL56-02S", id=528),
    DBLCharacter(name=" Bergamo", charatags="DBL56-04E", id=529),
    DBLCharacter(name="Super Saiyan Kale (Berserk)", charatags="DBL56-03E", id=530),
    DBLCharacter(name="Super Saiyan 2 Trunks (Adult)", charatags="DBL-EVT-63S", id=531),
    DBLCharacter(name="Super Saiyan Rosé Goku Black", charatags="DBL57-01U", id=532),
    DBLCharacter(name="Super Saiyan Trunks (Adult)", charatags="DBL57-02S", id=533),
    DBLCharacter(name="2nd Form Cell", charatags="DBL57-03S", id=534),
    DBLCharacter(name=" Pui Pui", charatags="DBL-EVT-64S", id=535),
    DBLCharacter(name="Super Saiyan 3 & Super Saiyan 2 Goku & Vegeta", charatags="DBL58-01S", id=536),
    DBLCharacter(name=" Buu: Kid", charatags="DBL58-03U", id=538),
    DBLCharacter(name=" Goku & Final Form Frieza", charatags="DBL59-01S", id=539),
    DBLCharacter(name=" Jiren", charatags="DBL59-04S", id=540),
    DBLCharacter(name=" Kahseral", charatags="DBL59-06S", id=541),
    DBLCharacter(name=" Kyawei", charatags="DBL59-05S", id=542),
    DBLCharacter(name="God of Destruction Champa", charatags="DBL59-02E", id=543),
    DBLCharacter(name=" Vados", charatags="DBL59-03E", id=544),
    DBLCharacter(name=" Ultimate Gohan", charatags="DBL-EVT-66S", id=545),
    DBLCharacter(name="Super Saiyan God SS Vegeta", charatags="DBL-EVT-67S", id=546),
    DBLCharacter(name="Final Form Cooler", charatags="DBL-EVT-68S", id=547),
    DBLCharacter(name=" Android #13", charatags="DBL-EVT-69S", id=548),
    DBLCharacter(name=" Gamma 1 & Gamma 2", charatags="DBL60-03S", id=549),
    DBLCharacter(name=" Magenta", charatags="DBL60-04S", id=550),
    DBLCharacter(name="Power Awakening Piccolo", charatags="DBL60-02S", id=551),
    DBLCharacter(name=" Gohan", charatags="DBL60-01S", id=552),
    DBLCharacter(name=" Goku Black", charatags="DBL-EVT-70S", id=553),
    DBLCharacter(name="Super Saiyan God SS Vegito", charatags="DBL61-01U", id=554),
    DBLCharacter(name="Perfect Form Cell", charatags="DBL61-03S", id=555),
    DBLCharacter(name="Super Saiyan Gohan (Youth)", charatags="DBL61-02S", id=556),
    DBLCharacter(name=" Cell Jr.", charatags="DBL61-04E", id=557),
    DBLCharacter(name=" Android #18", charatags="DBL-EVT-71S", id=558),
    DBLCharacter(name=" Goku", charatags="DBL-EVT-72S", id=559),
    DBLCharacter(name=" Captain Ginyu", charatags="DBL62-01S", id=560),
    DBLCharacter(name=" Jeice & Burter", charatags="DBL62-03S", id=561),
    DBLCharacter(name=" Recoome & Guldo", charatags="DBL62-02S", id=562),
    DBLCharacter(name="Super Saiyan Goku", charatags="DBL62-04S", id=563),
    DBLCharacter(name=" Gohan (Kid) & Krillin", charatags="DBL62-05E", id=564),
    DBLCharacter(name=" Goku (Youth)", charatags="DBL63-01S", id=565),
    DBLCharacter(name=" Android #8", charatags="DBL63-03S", id=566),
    DBLCharacter(name=" Master Roshi", charatags="DBL63-02S", id=567),
    DBLCharacter(name=" Goku", charatags="DBL63-04S", id=568),
    DBLCharacter(name=" Piccolo Jr.", charatags="DBL63-05S", id=569),
    DBLCharacter(name=" Demon King Piccolo", charatags="DBL-EVT-73S", id=570),
    DBLCharacter(name="Hero Tapion", charatags="DBL-EVT-74S", id=571),
    DBLCharacter(name=" Super Janemba", charatags="DBL64-01U", id=572),
    DBLCharacter(name=" Pikkon", charatags="DBL64-02S", id=573),
    DBLCharacter(name=" Metal Cooler", charatags="DBL64-03E", id=574),
    DBLCharacter(name="Super Saiyan Gohan (Youth)", charatags="DBL-EVT-75S", id=575),
    DBLCharacter(name="Super Saiyan God SS Evolved & Super Saiyan God SS Kaioken Vegeta & Goku", charatags="DBL65-01S", id=576),
    DBLCharacter(name=" Golden Frieza", charatags="DBL65-04S", id=577),
    DBLCharacter(name=" Ultimate Gohan", charatags="DBL65-02S", id=579),
    DBLCharacter(name=" Gotenks", charatags="DBL65-03S", id=580),
    DBLCharacter(name="Final Form Frieza", charatags="DBL-EVT-77S", id=582),
    DBLCharacter(name=" Goku & Bardock", charatags="DBL66-01S", id=583),
    DBLCharacter(name="Final Form Frieza", charatags="DBL66-03E", id=584),
    DBLCharacter(name=" Bardock", charatags="DBL66-02E", id=585),
    DBLCharacter(name="Ultra Instinct -Sign- Goku", charatags="DBL66-04U", id=586),
    DBLCharacter(name="God of Destruction Beerus", charatags="DBL-EVT-78S", id=587),
    DBLCharacter(name=" Goku", charatags="DBL67-01S", id=588),
    DBLCharacter(name=" Pan: Trunks & Giru (Assist)", charatags="DBL67-02S", id=589),
    DBLCharacter(name=" Trunks", charatags="DBL67-03E", id=590),
    DBLCharacter(name=" Bulla: Vegeta (Assist)", charatags="DBL67-04S", id=592),
    DBLCharacter(name="Red Ribbon Army Piccolo", charatags="DBL-EVT-76S", id=594),
    DBLCharacter(name=" Super #17", charatags="DBL67-05S", id=595),
    DBLCharacter(name="1st Form Cell", charatags="DBL-EVT-79S", id=596),
    DBLCharacter(name=" Super Vegeta", charatags="DBL68-01S", id=597),
    DBLCharacter(name=" Android #16", charatags="DBL68-02S", id=598),
    DBLCharacter(name="Super Saiyan 2 Gohan (Youth)", charatags="DBL68-03U", id=599),
    DBLCharacter(name=" Broly: Fury", charatags="DBL-EVT-80S", id=600),
    DBLCharacter(name=" Super Baby 2", charatags="DBL69-01S", id=601),
    DBLCharacter(name="Trunks (Parasitism) Baby", charatags="DBL69-02S", id=602),
]
